`CREATE TABLE last_logins (
id SERIAL PRIMARY KEY,
user_id VARCHAR(50) NOT NULL,
device VARCHAR(255) NOT NULL,
login_time TIMESTAMP NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(username)
);


CREATE TABLE users (
 id SERIAL PRIMARY KEY,
 username VARCHAR(50) UNIQUE NOT NULL,
 password VARCHAR(50) NOT NULL,
 role VARCHAR(50) NOT NULL
);`;
